### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [rinkodijks/potential-octo-enigma#2]
I'd like to use this project, but I don't know under which license it's released. Any chance you could release it under a permissive license?

**Comment by pchaigno** [comment]
@rinkodijks Did you get a chance to look into this?

**Comment by rinkodijks** [comment]
@pchaigno oh sorry I never use github. This isn't my project, but I don't really remember where I got it from or what it is lol. I'm sorry for replying so late, if you can't find the files anywhere else I'd say go ahead and use them.

**Comment by pchaigno** [comment]
Thanks for the reply.
